# Generated by Django 4.2.17 on 2025-01-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_publisher_alter_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='email',
        ),
    ]
