# Generated by Django 4.2.17 on 2025-01-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_reviewer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewers',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.reviewer'),
        ),
    ]
