# Generated by Django 4.2.17 on 2025-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='md5_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
